/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.internal.api;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class SpringbootMultithreadingExample {
    public static void main(String[] args) {
        SpringApplication.run(SpringbootMultithreadingExample.class, args);
    }
}
